# Generated by Django 4.1.3 on 2022-12-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apkfinal2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='remitente',
            field=models.CharField(max_length=100),
        ),
    ]
