# Generated by Django 4.1.3 on 2022-12-24 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apkfinal2', '0002_alter_mensajes_remitente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensajes',
        ),
    ]
