# Generated by Django 4.1.3 on 2023-01-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apkfinal2', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
