# Generated by Django 4.1.3 on 2023-01-02 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Apkfinal2', '0005_delete_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=500)),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('visto', models.BooleanField(default=False)),
                ('enviar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviado', to=settings.AUTH_USER_MODEL)),
                ('recibir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibido', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
