# Generated by Django 4.1.3 on 2023-01-02 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Apkfinal2', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='recibir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='para', to=settings.AUTH_USER_MODEL),
        ),
    ]
