# Generated by Django 4.1.3 on 2022-12-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApkFinal1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mensajes',
        ),
    ]
