# Generated by Django 4.1.3 on 2022-12-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ApkFinal1', '0002_delete_mensajes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Puesto', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
