# Generated by Django 4.1.3 on 2022-12-27 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApkFinal1', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajador',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='Edad',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='Puesto',
            new_name='puesto',
        ),
    ]
